# Generated by Django 3.1.6 on 2021-02-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_badge',
            field=models.BooleanField(default=False),
        ),
    ]
